const path = {
	HOME: '/',
	TRUYEN_TRANH: '/truyen-tranh/',
	TRUYEN_TRANH_DETAIL: '/truyen-tranh/:slug',
	XEM:'/truyen-tranh/xem/',
	TRUYEN_TRANH_VIEW: '/truyen-tranh/xem/:slug',
	TIM_KIEM_NANG_CAO: '/tim-truyen-nang-cao',
	ADMIN_LOGIN: '/admin/login',
	ADMIN_HOME: '/admin',
	THEO_DOI: '/theo-doi',
	HISTORY: '/lich-su',
	TRUYEN_CON_TRAI: '/truyen-con-trai',
	TRUYEN_CON_GAI: '/truyen-con-gai',
	TRUYEN_HOT:'/truyen-hot',
	APP:'/app',
	ADMIN_CATEGORY: '/admin/danh-muc',
	ADMIN_COMIC: '/admin/truyen',
	ADD_ADMIN_COMIC: '/admin/truyen/them-moi',
	TIM_TRUYEN: '/tim-truyen',
	TIM_TRUYEN_VIEW: '/tim-truyen:id',
	ADMIN_TAC_GIA:'/admin/tac-gia',
	ADD_ADMIN_CHAPTER_BASE: '/them-tap/',
	ADD_ADMIN_CHAPTER: '/them-tap/:comic_id',
	EDIT_ADMIN_COMIC_BASE: '/truyen/chinh-sua/',
	EDIT_ADMIN_COMIC: '/truyen/chinh-sua/:comic_id',
	EDIT_ADMIN_CHAPTER_BASE: '/truyen/chinh-sua-chapter/',
	EDIT_ADMIN_CHAPTER: '/truyen/chinh-sua-chapter/:chapter_id',
}

export default path
